export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const THUMB_UP_COMMENT = 'THUMB_UP_COMMENT';
export const THUMB_DOWN_COMMENT = 'THUMB_DOWN_COMMENT';
export const EDIT_FORM_SHOW = 'EDIT_COMMENT_SHOW';
export const EDIT_FORM_CHANGE = 'EDIT_COMMENT_CHANGE';
export const ADD_FORM_CHANGE = 'ADD_FORM_CHANGE';
